Boundary screen
egovernments/DIGIT-Frontend pull request #1451
Opened 2024-10-01 11:44 UTC by abishekTa-egov

Campaign Boundary screen for summary screen, ready to take data.

2024-10-01 13:32 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/CampaignBoundary.js
> +    const selectedData = [
Remove this

2024-10-01 13:33 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/CampaignBoundary.js
> +        }
@abishekTa-egov Update here

2024-10-01 13:33 UTC, nipunarora-eGov requested changes
@abishekTa-egov check codeRabbit comments and rectify them

2024-10-03 04:40 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/CampaignBoundary.js
> +import { unstable_batchedUpdates } from "react-dom";
What is this import?

2024-10-03 06:58 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/Sample.js
> +        "type": "District",
remove this file if not required

2024-10-03 07:14 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/css/src/components/microplan.scss
> +    display:"inline-flex";
this css is wrong, remove quotes

2024-10-03 07:28 UTC, abishekTa-egov reviewed
I have resolved all the comments

2024-10-03 07:28 UTC, abishekTa-egov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/CampaignBoundary.js
> +    const selectedData = [
I don't understand what to remove

2024-10-03 08:22 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/CampaignBoundary.js
> +    const selectedData=[
can you remove this hardcoded data

2024-10-03 08:23 UTC, nipunarora-eGov commented on health/micro-ui/web/public/index.html
> +<<<<<<< HEAD
Resolve this change

2024-10-03 10:11 UTC, nipunarora-eGov approved these changes

2024-10-03 10:12 UTC, nipunarora-eGov approved these changes

2024-10-03 11:45 UTC, merged