User Role being displayed in Pop, Plan and Fac
egovernments/DIGIT-Frontend pull request #1854
Opened 2024-11-18 12:31 UTC by abishekTa-egov

User Role being displayed in Pop, Plan and Fac and dropdown localizations

2024-11-19 05:30 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/pages/employee/PopInbox.js
> +          {`Logged in as ${t(userName)} - ${t(userRole)}`}
@abishekTa-egov how many times do we have to tell you to localise all the messages?

2024-11-19 06:20 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/configs/UICustomizations.js
> +            options = [{ code: "1", name: "MP_ACTIONS_VIEW_SUMMARY" }];
@abishekTa-egov check this point it's critical

2024-11-19 08:12 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/example/src/UICustomizations.js
> +            return <p>{t(Digit.Utils.locale.getTransformedLocale("MICROPLAN_STATUS_" + value))}</p>;
Make sure these changes are there in both UICustomizations.js files @abishekTa-egov

2024-11-19 08:12 UTC, nipunarora-eGov requested changes
Check comments + add facility unassign popup

2024-11-19 08:15 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/UserAccess.js
> +  const [unassignPopup, setUnassignPopup] = useState(false); // usually set to row value for true case
have you tested it? @abishekTa-egov 
declare this state at the top not here

2024-11-19 08:16 UTC, nipunarora-eGov requested changes
check comments

2024-11-19 09:03 UTC, nabeelmd-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/RoleTableComposer.js
>    const [isLoading, setIsLoading] = useState(null);
we dont need isLoading state. Remove this state and wherever you're doing setIsLoading

2024-11-19 09:03 UTC, nabeelmd-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/RoleTableComposer.js
>          setIsLoading(false);
remove setisloading

2024-11-19 09:03 UTC, nabeelmd-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/RoleTableComposer.js
> +        setIsLoading(false);
remove setisloading

2024-11-19 09:03 UTC, nabeelmd-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/RoleTableComposer.js
>          setIsLoading(false);
remove setisloading

2024-11-19 09:03 UTC, nabeelmd-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/RoleTableComposer.js
> +        setIsLoading(false);
remove setisloading

2024-11-19 09:03 UTC, nabeelmd-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/UserAccess.js
>          setIsLoading(false);
remove setisloading

2024-11-19 09:03 UTC, nabeelmd-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/UserAccess.js
>          setIsLoading(false);
remove setisloading

2024-11-19 09:03 UTC, nabeelmd-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/UserAccess.js
> +      {
remove loader

2024-11-20 09:03 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FacilityPopup.js
> +  const dummyData = {
change variable name

2024-11-20 09:03 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FacilityPopup.js
> +  const dummyData = {
after || instead of empty string write t("NA")

2024-11-20 09:04 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FacilityPopup.js
> +  const dummyData = {
keep this dummy data in some state and use that state variable to render

2024-11-20 09:05 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FacilityPopup.js
> +                      {key === "servingPopulation" ? (
create data to be array of objects instead of an object. Each item will be like {key:"",value:""}. Directly map over this state to render

2024-11-20 09:08 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/example/src/UICustomizations.js
> +            return <p>{t(Digit.Utils.locale.getTransformedLocale("MICROPLAN_TYPE_" + value))}</p>;
Make sure the same changes are there in other UICustomizations.js file

2024-11-20 09:08 UTC, nipunarora-eGov requested changes
check comments

2024-11-20 12:26 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FacilityPopup.js
> +  const dummyData = {
remove this

2024-11-20 12:29 UTC, nipunarora-eGov submitted a review, later dismissed

2024-11-21 07:04 UTC, nipunarora-eGov submitted a review, later dismissed

2024-11-21 07:25 UTC, nipunarora-eGov approved these changes

2024-11-21 07:45 UTC, nipunarora-eGov approved these changes

2024-11-21 07:45 UTC, merged