Employee search fix
egovernments/DIGIT-Frontend pull request #1892
Opened 2024-11-26 08:32 UTC by abishekTa-egov

Employee search fix

2024-11-26 08:35 UTC, nabeelmd-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/HypothesisWrapper.js
> +            console.log("hiiii");
remove consoel

2024-11-26 08:35 UTC, nabeelmd-eGov approved these changes
looks fine to me

2024-11-26 09:27 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfiguration.js
> +  const [wrongFormulaNameToast, setWrongFormulaNameToast] = useState(false);
@abishekTa-egov directly use setShowToast() why to keep seperate useless states

2024-11-26 09:29 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfiguration.js
> +        if (!(formulaToAdd?.name && /^[a-zA-Z0-9]*$/.test(formulaToAdd.name) && formulaToAdd.name.length < 100)) {
@abishekTa-egov check the onClick of yes button, there only perform these validations. Don't even come to this function

2024-11-26 09:30 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfiguration.js
> +            wrongFormulaNameToast &&  <Toast
this is not required use showToast state for all toasts @abishekTa-egov

2024-11-26 09:35 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/HypothesisWrapper.js
> +    const hasExceededUpperBound = visibleAssumptions.some((item) => {
dont't use visible assumptions here

2024-11-26 10:10 UTC, abishekTa-egov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfiguration.js
> +        if (!(formulaToAdd?.name && /^[a-zA-Z0-9]*$/.test(formulaToAdd.name) && formulaToAdd.name.length < 100)) {
This function is triggered on clicking yes button

2024-11-26 10:11 UTC, abishekTa-egov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfiguration.js
> +            wrongFormulaNameToast &&  <Toast
This is the only <Toast/> being used

2024-11-26 10:30 UTC, abishekTa-egov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfiguration.js
> +  const [wrongFormulaNameToast, setWrongFormulaNameToast] = useState(false);
Its the only toast being used

2024-11-26 10:32 UTC, abishekTa-egov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/HypothesisWrapper.js
> +    const hasExceededUpperBound = visibleAssumptions.some((item) => {
visibleAssumptions is the keys of the assumptionValues for the page being filled

2024-11-26 10:37 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfiguration.js
> +  const [wrongFormulaNameToast, setWrongFormulaNameToast] = useState(false);
@abishekTa-egov simply call setShowToast()

2024-11-26 10:37 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/FormulaConfiguration.js
> +        if (!(formulaToAdd?.name && /^[a-zA-Z0-9]*$/.test(formulaToAdd.name) && formulaToAdd.name.length < 100)) {
@abishekTa-egov read the comment carefully and update code

2024-11-26 10:38 UTC, nipunarora-eGov commented on health/micro-ui/web/micro-ui-internals/packages/modules/microplan/src/components/HypothesisWrapper.js
> +    const hasExceededUpperBound = visibleAssumptions.some((item) => {
We can check for all assumptions instead of this page to keep consistent logic @abishekTa-egov check the above hasNan function

2024-11-26 10:40 UTC, nipunarora-eGov requested changes
Check comments carefully and update the logic

2024-11-26 14:38 UTC, nipunarora-eGov approved these changes

2024-11-27 04:57 UTC, nipunarora-eGov approved these changes

2024-11-27 04:57 UTC, merged